version: '3'
services:
  dp-postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    env_file: ".env"
    networks:
      - backend
    volumes:
      - /tmp/postgresql:/var/lib/postgresql
      - /tmp/postgresql/data:/var/lib/postgresql/data
    restart: on-failure

  fastapi-app:
    build: .
    command: >
            sh -c "poetry run alembic upgrade head && poetry run fastapi run app/app.py"
    ports:
      - "80:8000"
    restart: on-failure
    networks:
      - backend
    depends_on:
      dp-postgres:
        condition: service_started

networks:
  backend:
    driver: bridge