version: '3'
services:
  dp-postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: appdbuser
      POSTGRES_PASSWORD: appuserpass
      POSTGRES_DB: fastapidb
    networks:
      - backend
#    volumes:
#      - ./db-data/:/var/lib/postgresql/data/
    restart: on-failure

  fastapi-app:
    build: .
    command: poetry run fastapi run app/app.py
    ports:
      - "8000:8000"
#    env_file:
#      - .env
    restart: on-failure
    networks:
      - backend
    depends_on:
      dp-postgres:
        condition: service_started

networks:
  backend:
    driver: bridge