"""add enum to postgres

Revision ID: 1d07dc95035b
Revises: a37f63bf9a7f
Create Date: 2024-07-13 18:11:37.848422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d07dc95035b'
down_revision: Union[str, None] = 'a37f63bf9a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    temp_enum = sa.Enum("MALE", "FEMALE", name="sex")
    temp_enum.create(op.get_bind(), checkfirst=False)

    op.alter_column(
        "users",
        "sex",
        existing_type=sa.VARCHAR(),
        type_=temp_enum,
        existing_nullable=False,
        postgresql_using="sex::sex",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sex',
               existing_type=sa.Enum('MALE', 'FEMALE', name='sex'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
